// paint.cc
#define IMG_WHEEL "themes/waifu/images/steering_wheel.png"
#define IMG_TURN "themes/waifu/images/traffic_sign_turn.png"
#define IMG_FACE "themes/waifu/images/driver_face.png"
#define IMG_MAP "themes/waifu/images/map.png"
#define IMG_BUTTON_SETTINGS "themes/waifu/images/button_settings.png"
#define IMG_BUTTON_HOME "themes/waifu/images/button_home.png"
#define IMG_BATTERY "themes/waifu/images/battery.png"
#define IMG_BATTERY_CHARGING "themes/waifu/images/battery_charging.png"
#define IMG_NETWORK "themes/waifu/images/network_%d.png"
