// paint.cc
#define COLOR_BG_STATUS_STOPPED {0x07, 0x23, 0x39, 0xff}
#define COLOR_BG_STATUS_DISENGAGED {0x17, 0x33, 0x49, 0xff}
#define COLOR_BG_STATUS_ENGAGED {0x17, 0x86, 0x44, 0xff}
#define COLOR_BG_STATUS_WARNING {0xDA, 0x6F, 0x25, 0xff}
#define COLOR_BG_STATUS_ALERT {0xC9, 0x22, 0x31, 0xff}

#define COLOR_ALERT_STATUS_STOPPED {0x07, 0x23, 0x39, 0xf1}
#define COLOR_ALERT_STATUS_DISENGAGED {0x17, 0x33, 0x49, 0xc8}
#define COLOR_ALERT_STATUS_ENGAGED {0x17, 0x86, 0x44, 0xf1}
#define COLOR_ALERT_STATUS_WARNING {0xDA, 0x6F, 0x25, 0xf1}
#define COLOR_ALERT_STATUS_ALERT {0xC9, 0x22, 0x31, 0xf1}

// draw_lead
#define COLOR_CHEVRON nvgRGBA(201, 34, 49, fillAlpha)
#define COLOR_CHEVRON_BORDER COLOR_YELLOW

// ui_draw_track
#define COLOR_TRACK_BG COLOR_WHITE
#define COLOR_TRACK_BG_ALPHA COLOR_WHITE_ALPHA(0)

// ui_draw_vision_maxspeed
#define COLOR_MAXSPEED_OVER_LIMIT_BG nvgRGBA(218, 111, 37, 180)
#define COLOR_MAXSPEED_UNDER_LIMIT_BG COLOR_BLACK_ALPHA(100)
#define COLOR_MAXSPEED_LIMIT_BORDER COLOR_WHITE_ALPHA(100)
#define COLOR_MAXSPEED_OVER_LIMIT COLOR_OCHRE
#define COLOR_MAXSPEED_EGO_OVER_LIMIT COLOR_WHITE_ALPHA(20)
#define COLOR_MAXSPEED_EGO_UNDER_LIMIT COLOR_WHITE
#define COLOR_MAXSPEED_CRUISE_SET_LABEL COLOR_WHITE_ALPHA(200)
#define COLOR_MAXSPEED_CRUISE_NOT_SET_LABEL COLOR_WHITE_ALPHA(100)
#define COLOR_MAXSPEED_CRUISE_SET COLOR_WHITE
#define COLOR_MAXSPEED_CRUISE_NOT_SET COLOR_WHITE_ALPHA(100)

#define COLOR_SPEEDLIMIT_BG COLOR_WHITE_ALPHA(100)
#define COLOR_SPEEDLIMIT_EGO_OVER_LIMIT_BG nvgRGBA(218, 111, 37, 180)
#define COLOR_SPEEDLIMIT_VALID_BG COLOR_WHITE

#define COLOR_SPEEDLIMIT_EGO_OVER_LIMIT_BORDER COLOR_OCHRE
#define COLOR_SPEEDLIMIT_EGO_UNDER_LIMIT_BORDER COLOR_WHITE

#define COLOR_SPEEDLIMIT_EGO_OVER_LIMIT_LABEL COLOR_WHITE
#define COLOR_SPEEDLIMIT_EGO_UNDER_LIMIT_LABEL COLOR_BLACK

#define COLOR_SPEEDLIMIT_EGO_OVER_LIMIT COLOR_WHITE
#define COLOR_SPEEDLIMIT_EGO_UNDER_LIMIT COLOR_BLACK

// ui_draw_vision_speed
#define COLOR_SPEED COLOR_WHITE
#define COLOR_SPEED_UNIT COLOR_WHITE_ALPHA(200)

// ui_draw_vision_event
#define COLOR_STEERING_WHEEL COLOR_BLACK_ALPHA(0)
#define COLOR_STEERING_WHEEL_STATUS_ENGAGED nvgRGBA(23, 134, 68, 255)
#define COLOR_STEERING_WHEEL_STATUS_WARNING COLOR_OCHRE
#define COLOR_STEERING_WHEEL_STATUS_DISENGAGED nvgRGBA(23, 51, 73, 255)

// ui_draw_driver_view
#define COLOR_DRIVER_BG_FROM COLOR_BLACK
#define COLOR_DRIVER_BG_TO COLOR_BLACK_ALPHA(0)
#define COLOR_DRIVER_BG_ALPHA COLOR_BLACK_ALPHA(144)

#define COLOR_DRIVER_BORDER_OUT nvgRGBA(23, 51, 73, 255)
#define COLOR_DRIVER_BORDER_IN nvgRGBA(23, 51, 73, 255)

// ui_draw_vision_alert
#define COLOR_ALERT_BG COLOR_WHITE
#define COLOR_ALERT COLOR_WHITE

// text/text.c 
// main
#define COLOR_TEXT COLOR_WHITE
#define COLOR_TEXT_BG nvgRGBA(0, 0, 0, 175)
#define COLOR_TEXT_BG_ALPHA nvgRGBA(0, 0, 0, 255)

#define COLOR_BUTTON_BG nvgRGBA(8, 8, 8, 255)
#define COLOR_BUTTON_LABEL nvgRGBA(255, 255, 255, 255)
#define COLOR_BUTTON_BORDER nvgRGBA(255, 255, 255, 50)
